# Generated by Django 3.1.8 on 2021-08-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210820_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='deposits',
        ),
        migrations.AddField(
            model_name='deposits',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_wallet', to='user.wallet'),
        ),
    ]
