# Generated by Django 3.1.8 on 2021-08-20 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210820_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposits',
            name='wallet',
        ),
        migrations.AddField(
            model_name='deposits',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
