# Generated by Django 3.2.6 on 2021-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210821_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='amount',
            field=models.IntegerField(max_length=5),
        ),
    ]
